// FIZIK soru havuzu: 100 soru (30 kolay / 50 orta / 20 zor), 9. sinif MEB mufredati, kisa sorular (g = 10 m/s²).
// Format: { id, difficulty: 'easy' | 'medium' | 'hard', question, answers: {A,B,C,D}, correct: 'A'..'D' }
module.exports = [
  { id: 'fiz_001', difficulty: 'medium', question: "100 J'lük işi 4 s'de yapan makinenin gücü kaç W'tır?", answers: { A: "25", B: "400", C: "104", D: "0,04" }, correct: 'A' },
  { id: 'fiz_002', difficulty: 'easy', question: "2 kg kaç gramdır?", answers: { A: "20", B: "200", C: "20000", D: "2000" }, correct: 'D' },
  { id: 'fiz_003', difficulty: 'hard', question: "10 m/s hızla giden cisim 5 m/s² büyüklüğünde ivmeyle yavaşlıyor. Durana kadar kaç m yol alır?", answers: { A: "20", B: "5", C: "10", D: "50" }, correct: 'C' },
  { id: 'fiz_004', difficulty: 'medium', question: "Hız-zaman grafiğinde eğrinin altında kalan alan neyi verir?", answers: { A: "Yer değiştirmeyi", B: "İvmeyi", C: "Kuvveti", D: "Sıcaklığı" }, correct: 'A' },
  { id: 'fiz_005', difficulty: 'medium', question: "Isıtılan bir kapta sıcak suyun yükselip soğuk suyun alçalması hangi yolla ısı yayılmasıdır?", answers: { A: "İletim", B: "Işıma", C: "Konveksiyon (taşınım)", D: "Erime" }, correct: 'C' },
  { id: 'fiz_006', difficulty: 'medium', question: "Newton (N) birimi temel birimlerle nasıl ifade edilir?", answers: { A: "kg·m/s", B: "kg/m²", C: "kg·s/m", D: "kg·m/s²" }, correct: 'D' },
  { id: 'fiz_007', difficulty: 'medium', question: "Zıt yönlü 9 N ve 4 N'luk kuvvetlerin bileşkesi kaç N'dur?", answers: { A: "13", B: "36", C: "4", D: "5" }, correct: 'D' },
  { id: 'fiz_008', difficulty: 'medium', question: "Durgun halden 5 m/s² ivmeyle hızlanan cismin 4 s sonraki hızı kaç m/s'dir?", answers: { A: "9", B: "1,25", C: "20", D: "54" }, correct: 'C' },
  { id: 'fiz_009', difficulty: 'easy', question: "Zaman ölçmek için hangi alet kullanılır?", answers: { A: "Termometre", B: "Kronometre", C: "Dinamometre", D: "Barometre" }, correct: 'B' },
  { id: 'fiz_010', difficulty: 'medium', question: "Kütlesi 4 kg olan cisme 3 m/s² ivme kazandırmak için kaç N net kuvvet gerekir?", answers: { A: "7", B: "0,75", C: "24", D: "12" }, correct: 'D' },
  { id: 'fiz_011', difficulty: 'easy', question: "Kütlenin SI birimi hangisidir?", answers: { A: "Newton (N)", B: "litre (L)", C: "metre (m)", D: "kilogram (kg)" }, correct: 'D' },
  { id: 'fiz_012', difficulty: 'hard', question: "1 kg kütleli cisme birbirine dik 3 N ve 4 N'luk kuvvetler etki ediyor. İvmesi kaç m/s²'dir?", answers: { A: "5", B: "7", C: "1", D: "12" }, correct: 'A' },
  { id: 'fiz_013', difficulty: 'medium', question: "Kütlesi 2 kg olan cisme etki eden net kuvvet 12 N ise ivmesi kaç m/s²'dir?", answers: { A: "24", B: "6", C: "10", D: "0,17" }, correct: 'B' },
  { id: 'fiz_014', difficulty: 'medium', question: "Hızı 10 m/s'den 30 m/s'ye 5 saniyede çıkan cismin ivmesi kaç m/s²'dir?", answers: { A: "8", B: "4", C: "6", D: "2" }, correct: 'B' },
  { id: 'fiz_015', difficulty: 'medium', question: "Güneş'ten Dünya'ya ısı hangi yolla ulaşır?", answers: { A: "İletim", B: "Konveksiyon", C: "Genleşme", D: "Işıma" }, correct: 'D' },
  { id: 'fiz_016', difficulty: 'easy', question: "Aşağıdakilerden hangisi vektörel bir niceliktir?", answers: { A: "Hız", B: "Sürat", C: "Kütle", D: "Zaman" }, correct: 'A' },
  { id: 'fiz_017', difficulty: 'hard', question: "Yoğunluğu 2 g/cm³ olan 100 cm³ sıvı ile yoğunluğu 1 g/cm³ olan 100 cm³ sıvı karıştırılıyor. Karışımın yoğunluğu kaç g/cm³ olur?", answers: { A: "1,5", B: "1", C: "2", D: "3" }, correct: 'A' },
  { id: 'fiz_018', difficulty: 'hard', question: "Bileşkeleri en az 2 N, en çok 14 N olabilen iki kuvvet hangisidir?", answers: { A: "10 N ve 4 N", B: "8 N ve 6 N", C: "7 N ve 7 N", D: "9 N ve 5 N" }, correct: 'B' },
  { id: 'fiz_019', difficulty: 'medium', question: "Aynı cins moleküller arasındaki çekim kuvvetine ne denir?", answers: { A: "Kohezyon", B: "Adezyon", C: "Sürtünme", D: "Genleşme" }, correct: 'A' },
  { id: 'fiz_020', difficulty: 'hard', question: "Dünya'da ağırlığı 600 N olan astronotun, yer çekimi ivmesi Dünya'dakinin 1/6'sı olan Ay'daki ağırlığı kaç N'dur?", answers: { A: "600", B: "3600", C: "100", D: "10" }, correct: 'C' },
  { id: 'fiz_021', difficulty: 'hard', question: "20 m/s hızla düşey yukarı atılan cisim en fazla kaç m yükselir? (g = 10 m/s², sürtünme yok)", answers: { A: "40", B: "10", C: "20", D: "5" }, correct: 'C' },
  { id: 'fiz_022', difficulty: 'easy', question: "Uzunluğun SI birimi hangisidir?", answers: { A: "metre", B: "kilogram", C: "saniye", D: "kelvin" }, correct: 'A' },
  { id: 'fiz_023', difficulty: 'medium', question: "0 °C yaklaşık kaç Kelvin'dir?", answers: { A: "273", B: "0", C: "373", D: "−273" }, correct: 'A' },
  { id: 'fiz_024', difficulty: 'medium', question: "Serbest bırakılan cismin 2 s sonraki hızı kaç m/s'dir? (g = 10 m/s², sürtünme yok)", answers: { A: "5", B: "20", C: "10", D: "40" }, correct: 'B' },
  { id: 'fiz_025', difficulty: 'medium', question: "Kütlesi 2 kg olan cismin 5 m/s hızla kinetik enerjisi kaç J'dür?", answers: { A: "25", B: "50", C: "10", D: "5" }, correct: 'A' },
  { id: 'fiz_026', difficulty: 'hard', question: "5 m yükseklikten serbest bırakılan cismin yere çarpma hızı kaç m/s'dir? (g = 10 m/s², sürtünme yok)", answers: { A: "5", B: "50", C: "100", D: "10" }, correct: 'D' },
  { id: 'fiz_027', difficulty: 'easy', question: "Zamanın SI birimi hangisidir?", answers: { A: "dakika", B: "saat", C: "saniye", D: "gün" }, correct: 'C' },
  { id: 'fiz_028', difficulty: 'easy', question: "Suyun normal koşullarda donma sıcaklığı kaç °C'dir?", answers: { A: "0", B: "100", C: "−10", D: "10" }, correct: 'A' },
  { id: 'fiz_029', difficulty: 'medium', question: "Sıvı basıncı hangi niceliklere bağlıdır?", answers: { A: "Derinliğe ve sıvının yoğunluğuna", B: "Kabın şekline", C: "Kabın rengine", D: "Kabın hacmine" }, correct: 'A' },
  { id: 'fiz_030', difficulty: 'easy', question: "Gaz bir maddenin sıvıya geçmesine ne denir?", answers: { A: "Yoğuşma", B: "Buharlaşma", C: "Erime", D: "Süblimleşme" }, correct: 'A' },
  { id: 'fiz_031', difficulty: 'easy', question: "Aşağıdakilerden hangisi skaler bir niceliktir?", answers: { A: "Kuvvet", B: "Hız", C: "Kütle", D: "Yer değiştirme" }, correct: 'C' },
  { id: 'fiz_032', difficulty: 'easy', question: "Dengelenmiş kuvvetlerin etkisindeki cismin net kuvveti kaçtır?", answers: { A: "Sonsuz", B: "0", C: "Ağırlığına eşit", D: "Kütlesine eşit" }, correct: 'B' },
  { id: 'fiz_033', difficulty: 'medium', question: "Hareket eden otobüs ani fren yapınca ayakta duran yolcular ne olur?", answers: { A: "Arkaya doğru savrulur", B: "Öne doğru savrulur", C: "Yana savrulur", D: "Hiçbir şey olmaz" }, correct: 'B' },
  { id: 'fiz_034', difficulty: 'easy', question: "Sürtünme kuvveti cismin hareketine göre hangi yöndedir?", answers: { A: "Aynı yönde", B: "Dik yönde", C: "Ters yönde", D: "Yönü yoktur" }, correct: 'C' },
  { id: 'fiz_035', difficulty: 'hard', question: "Bir araç 4 m/s hızla 5 s, ardından 8 m/s hızla 5 s gidiyor. Ortalama sürati kaç m/s'dir?", answers: { A: "5", B: "7", C: "12", D: "6" }, correct: 'D' },
  { id: 'fiz_036', difficulty: 'hard', question: "2 kg'lık cisme zıt yönlü 10 N ve 4 N'luk kuvvetler etki ediyor. İvmesi kaç m/s²'dir?", answers: { A: "3", B: "7", C: "14", D: "2" }, correct: 'A' },
  { id: 'fiz_037', difficulty: 'medium', question: "Tren raylarının arasında boşluk bırakılmasının nedeni nedir?", answers: { A: "Genleşme", B: "Yoğuşma", C: "Erime", D: "Kırılma" }, correct: 'A' },
  { id: 'fiz_038', difficulty: 'medium', question: "Su damlasının cama yapışmasında etkili olan kuvvet hangisidir?", answers: { A: "Kohezyon", B: "Sürtünme", C: "Kaldırma", D: "Adezyon" }, correct: 'D' },
  { id: 'fiz_039', difficulty: 'easy', question: "Sıcaklığı ölçmek için hangi alet kullanılır?", answers: { A: "Kronometre", B: "Termometre", C: "Dinamometre", D: "Metre" }, correct: 'B' },
  { id: 'fiz_040', difficulty: 'hard', question: "Bir araç yolun yarısını 30 km/sa, kalan yarısını 60 km/sa hızla gidiyor. Ortalama sürati kaç km/sa'dir?", answers: { A: "45", B: "40", C: "50", D: "30" }, correct: 'B' },
  { id: 'fiz_041', difficulty: 'medium', question: "Cisme etki eden kuvvet sabitken temas yüzeyi küçülürse basınç nasıl değişir?", answers: { A: "Azalır", B: "Değişmez", C: "Artar", D: "Sıfır olur" }, correct: 'C' },
  { id: 'fiz_042', difficulty: 'medium', question: "Saf bir madde hâl değiştirirken sıcaklığı nasıl değişir?", answers: { A: "Sabit kalır", B: "Sürekli artar", C: "Sürekli azalır", D: "Önce artar sonra azalır" }, correct: 'A' },
  { id: 'fiz_043', difficulty: 'easy', question: "Enerjinin SI birimi hangisidir?", answers: { A: "Newton", B: "Watt", C: "Joule", D: "Pascal" }, correct: 'C' },
  { id: 'fiz_044', difficulty: 'easy', question: "Hareketli bir cismin sahip olduğu enerjiye ne denir?", answers: { A: "Potansiyel enerji", B: "Kinetik enerji", C: "Isı enerjisi", D: "Işık enerjisi" }, correct: 'B' },
  { id: 'fiz_045', difficulty: 'easy', question: "Yoğunluğun SI birimi hangisidir?", answers: { A: "N/m", B: "m/s", C: "J/s", D: "kg/m³" }, correct: 'D' },
  { id: 'fiz_046', difficulty: 'medium', question: "Isı ve sıcaklık için hangisi doğrudur?", answers: { A: "Isı ile sıcaklık aynı niceliktir.", B: "Isı termometreyle ölçülür.", C: "Sıcaklığın birimi joule'dür.", D: "Sıcaklık, taneciklerin ortalama kinetik enerjisinin göstergesidir." }, correct: 'D' },
  { id: 'fiz_047', difficulty: 'easy', question: "Eylemsizlik ilkesi, Newton'un hangi yasasıdır?", answers: { A: "İkinci yasa", B: "Üçüncü yasa", C: "Yerçekimi yasası", D: "Birinci yasa" }, correct: 'D' },
  { id: 'fiz_048', difficulty: 'medium', question: "Sabit hızla giden araç 2 saatte 150 km yol alıyorsa hızı kaç km/sa'dir?", answers: { A: "300", B: "152", C: "75", D: "50" }, correct: 'C' },
  { id: 'fiz_049', difficulty: 'medium', question: "5 kg'lık cisme 20 N kuvvet, ters yönde 5 N sürtünme etki ediyor. İvme kaç m/s²'dir?", answers: { A: "4", B: "5", C: "3", D: "2" }, correct: 'C' },
  { id: 'fiz_050', difficulty: 'easy', question: "Gücün SI birimi hangisidir?", answers: { A: "Watt", B: "Joule", C: "Newton", D: "Kelvin" }, correct: 'A' },
  { id: 'fiz_051', difficulty: 'medium', question: "Aynı yönlü 6 N ve 8 N'luk kuvvetlerin bileşkesi kaç N'dur?", answers: { A: "2", B: "14", C: "10", D: "48" }, correct: 'B' },
  { id: 'fiz_052', difficulty: 'medium', question: "Dünya'da 60 kg olan bir insanın kütlesi Ay'da kaç kg olur?", answers: { A: "60", B: "10", C: "360", D: "600" }, correct: 'A' },
  { id: 'fiz_053', difficulty: 'medium', question: "10 N'luk kuvvet cismi kuvvet yönünde 5 m götürürse yapılan iş kaç J'dür?", answers: { A: "2", B: "15", C: "50", D: "5" }, correct: 'C' },
  { id: 'fiz_054', difficulty: 'medium', question: "Mekanik enerji neye eşittir?", answers: { A: "Kinetik − potansiyel enerji", B: "Yalnızca ısı enerjisi", C: "Kuvvet × zaman", D: "Kinetik + potansiyel enerji" }, correct: 'D' },
  { id: 'fiz_055', difficulty: 'hard', question: "Bir makine 800 J enerji alıp 600 J iş yapıyor. Verimi yüzde kaçtır?", answers: { A: "60", B: "80", C: "75", D: "25" }, correct: 'C' },
  { id: 'fiz_056', difficulty: 'medium', question: "Metal çubuğun bir ucu ısıtılınca diğer ucunun da ısınması hangi yolla olur?", answers: { A: "Konveksiyon", B: "Işıma", C: "İletim", D: "Yoğuşma" }, correct: 'C' },
  { id: 'fiz_057', difficulty: 'hard', question: "4 kg'lık cisme 20 N kuvvet, ters yönde 8 N sürtünme etki ediyor. Durgun cismin 3 s sonraki hızı kaç m/s'dir?", answers: { A: "12", B: "9", C: "5", D: "15" }, correct: 'B' },
  { id: 'fiz_058', difficulty: 'medium', question: "Ali önce 6 m doğuya, sonra 2 m batıya yürüyor. Yer değiştirmesi kaç m'dir?", answers: { A: "8", B: "4", C: "12", D: "6" }, correct: 'B' },
  { id: 'fiz_059', difficulty: 'medium', question: "Aşağıdakilerden hangisi türetilmiş bir niceliktir?", answers: { A: "Uzunluk", B: "Kütle", C: "Zaman", D: "Hız" }, correct: 'D' },
  { id: 'fiz_060', difficulty: 'medium', question: "Yoğunluğu suyunkinden küçük olan cisim suya bırakılırsa ne olur?", answers: { A: "Batar", B: "Yüzer", C: "Askıda kalır", D: "Erir" }, correct: 'B' },
  { id: 'fiz_061', difficulty: 'medium', question: "Konum-zaman grafiği eğimli bir doğru ise hareket nasıldır?", answers: { A: "Sabit ivmeli", B: "Duran", C: "Yavaşlayan", D: "Sabit hızlı" }, correct: 'D' },
  { id: 'fiz_062', difficulty: 'easy', question: "Sıcaklığın SI birimi hangisidir?", answers: { A: "Celsius", B: "Joule", C: "Kelvin", D: "Watt" }, correct: 'C' },
  { id: 'fiz_063', difficulty: 'easy', question: "Sıvı bir maddenin gaza geçmesine ne denir?", answers: { A: "Erime", B: "Buharlaşma", C: "Yoğuşma", D: "Donma" }, correct: 'B' },
  { id: 'fiz_064', difficulty: 'medium', question: "100 N'luk kuvvet 2 m² yüzeye dik etki ediyorsa basınç kaç Pa'dır?", answers: { A: "200", B: "50", C: "98", D: "0,02" }, correct: 'B' },
  { id: 'fiz_065', difficulty: 'medium', question: "Kütlesi 4 kg olan cismin 3 m yükseklikteki potansiyel enerjisi kaç J'dür? (g = 10 m/s²)", answers: { A: "12", B: "40", C: "120", D: "60" }, correct: 'C' },
  { id: 'fiz_066', difficulty: 'hard', question: "200 g suyun sıcaklığını 10 °C artırmak için kaç cal ısı gerekir? (c(su) = 1 cal/g·°C)", answers: { A: "2000", B: "200", C: "20", D: "210" }, correct: 'A' },
  { id: 'fiz_067', difficulty: 'medium', question: "Isının SI birimi hangisidir?", answers: { A: "Joule", B: "Kelvin", C: "Watt", D: "Newton" }, correct: 'A' },
  { id: 'fiz_068', difficulty: 'medium', question: "Sıvıda yüzen cismin ağırlığı ile kaldırma kuvveti arasındaki ilişki nedir?", answers: { A: "Ağırlık büyüktür", B: "Kaldırma kuvveti sıfırdır", C: "Kaldırma kuvveti iki katıdır", D: "Eşittir" }, correct: 'D' },
  { id: 'fiz_069', difficulty: 'medium', question: "Bilimsel yöntemde hipotez nedir?", answers: { A: "Kesinleşmiş yasa", B: "Deney sonucu", C: "Sınanabilir ön tahmin", D: "Doğrulanmış kuram" }, correct: 'C' },
  { id: 'fiz_070', difficulty: 'medium', question: "Yoğunluğu 2 g/cm³ olan 50 cm³ hacimli cismin kütlesi kaç g'dır?", answers: { A: "25", B: "100", C: "52", D: "250" }, correct: 'B' },
  { id: 'fiz_071', difficulty: 'medium', question: "10 saniyede 50 m yol alan cismin sürati kaç m/s'dir?", answers: { A: "500", B: "5", C: "0,2", D: "60" }, correct: 'B' },
  { id: 'fiz_072', difficulty: 'hard', question: "Hacmi 0,002 m³ olan cisim tamamen suya batırılıyor. Kaldırma kuvveti kaç N olur? (d(su) = 1000 kg/m³, g = 10 m/s²)", answers: { A: "2", B: "200", C: "0,2", D: "20" }, correct: 'D' },
  { id: 'fiz_073', difficulty: 'easy', question: "Sabit 20 m/s hızla giden cisim 3 saniyede kaç metre yol alır?", answers: { A: "60", B: "6", C: "23", D: "66" }, correct: 'A' },
  { id: 'fiz_074', difficulty: 'hard', question: "Ağırlığı 600 N olan kişinin iki ayağının toplam taban alanı 0,03 m² ise yere uyguladığı basınç kaç Pa'dır?", answers: { A: "18", B: "20000", C: "2000", D: "200" }, correct: 'B' },
  { id: 'fiz_075', difficulty: 'medium', question: "72 km/sa hız kaç m/s'dir?", answers: { A: "72", B: "7,2", C: "20", D: "259" }, correct: 'C' },
  { id: 'fiz_076', difficulty: 'medium', question: "Sıvıya batırılan cisme etki eden kaldırma kuvveti neye eşittir?", answers: { A: "Taşırdığı sıvının ağırlığına", B: "Cismin kütlesine", C: "Sıvının hacmine", D: "Cismin yoğunluğuna" }, correct: 'A' },
  { id: 'fiz_077', difficulty: 'easy', question: "Hızın SI birimi hangisidir?", answers: { A: "m/s", B: "kg/m³", C: "N", D: "J" }, correct: 'A' },
  { id: 'fiz_078', difficulty: 'easy', question: "Isı kendiliğinden hangi yönde akar?", answers: { A: "Soğuk cisimden sıcak cisme", B: "Her iki yönde eşit", C: "Akmaz", D: "Sıcak cisimden soğuk cisme" }, correct: 'D' },
  { id: 'fiz_079', difficulty: 'easy', question: "Ağırlık hangi aletle ölçülür?", answers: { A: "Termometre", B: "Dinamometre", C: "Barometre", D: "Kronometre" }, correct: 'B' },
  { id: 'fiz_080', difficulty: 'medium', question: "Aynı kütleli ve aynı ısıyı alan iki maddeden öz ısısı küçük olanın sıcaklığı nasıl değişir?", answers: { A: "Daha az artar", B: "Değişmez", C: "Azalır", D: "Daha çok artar" }, correct: 'D' },
  { id: 'fiz_081', difficulty: 'easy', question: "Yoğunluğu suyunkinden büyük bir cisim suya bırakılırsa ne olur?", answers: { A: "Yüzer", B: "Batar", C: "Askıda kalır", D: "Buharlaşır" }, correct: 'B' },
  { id: 'fiz_082', difficulty: 'hard', question: "50 °C kaç Kelvin'dir? (T(K) = t(°C) + 273)", answers: { A: "323", B: "223", C: "50", D: "373" }, correct: 'A' },
  { id: 'fiz_083', difficulty: 'medium', question: "Havasız ortamda aynı yükseklikten bırakılan taş ile tüy için hangisi doğrudur?", answers: { A: "Taş önce çarpar", B: "Tüy önce çarpar", C: "İkisi de düşmez", D: "Aynı anda yere çarparlar" }, correct: 'D' },
  { id: 'fiz_084', difficulty: 'easy', question: "Suyun normal koşullarda kaynama sıcaklığı kaç °C'dir?", answers: { A: "100", B: "0", C: "50", D: "212" }, correct: 'A' },
  { id: 'fiz_085', difficulty: 'hard', question: "Kütlesi 50 kg olan yükü 10 s'de 4 m yükseğe çıkaran motorun gücü kaç W'tır? (g = 10 m/s²)", answers: { A: "2000", B: "20", C: "500", D: "200" }, correct: 'D' },
  { id: 'fiz_086', difficulty: 'easy', question: "Katı bir maddenin sıvıya geçmesine ne denir?", answers: { A: "Donma", B: "Erime", C: "Buharlaşma", D: "Yoğuşma" }, correct: 'B' },
  { id: 'fiz_087', difficulty: 'medium', question: "Birbirine dik 3 N ve 4 N'luk kuvvetlerin bileşkesi kaç N'dur?", answers: { A: "7", B: "1", C: "5", D: "12" }, correct: 'C' },
  { id: 'fiz_088', difficulty: 'medium', question: "Sürtünmesiz ortamda serbest düşen cisimde yükseklik azaldıkça enerji nasıl değişir?", answers: { A: "Kinetik azalır, potansiyel artar", B: "Kinetik artar, potansiyel azalır", C: "İkisi de artar", D: "İkisi de azalır" }, correct: 'B' },
  { id: 'fiz_089', difficulty: 'medium', question: "Kütlesi 300 g, hacmi 100 cm³ olan cismin yoğunluğu kaç g/cm³'tür?", answers: { A: "0,33", B: "3", C: "30", D: "200" }, correct: 'B' },
  { id: 'fiz_090', difficulty: 'easy', question: "'Her etkiye eşit ve zıt yönlü bir tepki vardır.' ifadesi hangi yasadır?", answers: { A: "Newton'un birinci yasası", B: "Newton'un ikinci yasası", C: "Enerjinin korunumu", D: "Newton'un üçüncü yasası" }, correct: 'D' },
  { id: 'fiz_091', difficulty: 'medium', question: "Kütlesi 5 kg olan cisme 20 N net kuvvet etki ediyor. İvmesi kaç m/s²'dir?", answers: { A: "100", B: "15", C: "4", D: "0,25" }, correct: 'C' },
  { id: 'fiz_092', difficulty: 'medium', question: "Verimi %80 olan makineye 500 J enerji verilirse yararlı enerji kaç J olur?", answers: { A: "400", B: "100", C: "625", D: "580" }, correct: 'A' },
  { id: 'fiz_093', difficulty: 'hard', question: "Hız-zaman grafiğinde cisim 4 s'de düzgün biçimde 0'dan 10 m/s'ye çıkıyor. Bu sürede aldığı yol kaç m'dir?", answers: { A: "40", B: "20", C: "10", D: "2,5" }, correct: 'B' },
  { id: 'fiz_094', difficulty: 'medium', question: "Işık enerjisini elektrik enerjisine dönüştüren düzenek hangisidir?", answers: { A: "Güneş pili", B: "Jeneratör", C: "Ütü", D: "Hoparlör" }, correct: 'A' },
  { id: 'fiz_095', difficulty: 'medium', question: "Kütlesi 10 kg olan cismin ağırlığı kaç N'dur? (g = 10 m/s²)", answers: { A: "10", B: "100", C: "1", D: "1000" }, correct: 'B' },
  { id: 'fiz_096', difficulty: 'easy', question: "Kuvvetin SI birimi hangisidir?", answers: { A: "Joule", B: "Watt", C: "Pascal", D: "Newton" }, correct: 'D' },
  { id: 'fiz_097', difficulty: 'hard', question: "60 kg kütleli bir kişi, 2 m/s² ivmeyle yukarı hızlanan asansörde durmaktadır. Zemine uyguladığı kuvvet kaç N'dur? (g = 10 m/s²)", answers: { A: "600", B: "480", C: "120", D: "720" }, correct: 'D' },
  { id: 'fiz_098', difficulty: 'hard', question: "Durgun halden 2 m/s² ivmeyle hızlanan cisim 5 s'de kaç m yol alır?", answers: { A: "10", B: "50", C: "25", D: "20" }, correct: 'C' },
  { id: 'fiz_099', difficulty: 'easy', question: "F = m·a bağıntısı hangi yasanın ifadesidir?", answers: { A: "Newton'un birinci yasası", B: "Newton'un üçüncü yasası", C: "Newton'un ikinci yasası", D: "Arşimet ilkesi" }, correct: 'C' },
  { id: 'fiz_100', difficulty: 'easy', question: "5 km kaç metredir?", answers: { A: "50", B: "500", C: "5000", D: "50000" }, correct: 'C' },
];
